# fly.toml app configuration file generated for backend-web-4b5e57 on 2024-11-18T17:11:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-web-4b5e57'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile.backend'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
