/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsingModuleComponentRouteImport } from './routes/using-module-component'
import { Route as N8nRouteImport } from './routes/n8n'
import { Route as LoginRouteImport } from './../../modules/auth/frontend/src/routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './../../modules/auth/frontend/src/routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StripeIndexRouteImport } from './../../modules/stripe/frontend/src/routes/stripe/index'
import { Route as InvoicesIndexRouteImport } from './../../modules/stripe/frontend/src/routes/invoices/index'
import { Route as ExampleIndexRouteImport } from './../../modules/template/frontend/src/routes/example/index'
import { Route as AuthLogoutRouteImport } from './../../modules/auth/frontend/src/routes/_auth/logout'
import { Route as AuthDashboardRouteImport } from './routes/_auth/_dashboard'
import { Route as AuthDashboardSettingsRouteImport } from './routes/_auth/_dashboard/settings'
import { Route as AuthDashboardIntroFlowRouteImport } from './routes/_auth/_dashboard/intro-flow'
import { Route as AuthDashboardDashboardRouteImport } from './routes/_auth/_dashboard/dashboard'
import { Route as AuthDashboardProjectsIndexRouteImport } from './routes/_auth/_dashboard/projects/index'
import { Route as AuthDashboardProjectsProjectIdRouteRouteImport } from './routes/_auth/_dashboard/projects/$projectId/route'
import { Route as AuthDashboardProjectsProjectIdIndexRouteImport } from './routes/_auth/_dashboard/projects/$projectId/index'
import { Route as AuthDashboardProjectsProjectIdSettingsRouteRouteImport } from './routes/_auth/_dashboard/projects/$projectId/settings/route'
import { Route as AuthDashboardProjectsProjectIdSettingsIndexRouteImport } from './routes/_auth/_dashboard/projects/$projectId/settings/index'
import { Route as AuthDashboardProjectsProjectIdDeploymentsIndexRouteImport } from './routes/_auth/_dashboard/projects/$projectId/deployments/index'
import { Route as AuthDashboardProjectsProjectIdSettingsGeneralRouteImport } from './routes/_auth/_dashboard/projects/$projectId/settings/general'
import { Route as AuthDashboardProjectsProjectIdSettingsEnvironmentRouteImport } from './routes/_auth/_dashboard/projects/$projectId/settings/environment'
import { Route as AuthDashboardProjectsProjectIdSettingsDomainsRouteImport } from './routes/_auth/_dashboard/projects/$projectId/settings/domains'
import { Route as AuthDashboardProjectsProjectIdDeploymentsDeploymentIdIndexRouteImport } from './routes/_auth/_dashboard/projects/$projectId/deployments/$deploymentId/index'

const UsingModuleComponentRoute = UsingModuleComponentRouteImport.update({
  id: '/using-module-component',
  path: '/using-module-component',
  getParentRoute: () => rootRouteImport,
} as any)
const N8nRoute = N8nRouteImport.update({
  id: '/n8n',
  path: '/n8n',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeIndexRoute = StripeIndexRouteImport.update({
  id: '/stripe/',
  path: '/stripe/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleIndexRoute = ExampleIndexRouteImport.update({
  id: '/example/',
  path: '/example/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardSettingsRoute = AuthDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardIntroFlowRoute = AuthDashboardIntroFlowRouteImport.update({
  id: '/intro-flow',
  path: '/intro-flow',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardDashboardRoute = AuthDashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardProjectsIndexRoute =
  AuthDashboardProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardProjectsProjectIdRouteRoute =
  AuthDashboardProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardProjectsProjectIdIndexRoute =
  AuthDashboardProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardProjectsProjectIdRouteRoute,
  } as any)
const AuthDashboardProjectsProjectIdSettingsRouteRoute =
  AuthDashboardProjectsProjectIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthDashboardProjectsProjectIdRouteRoute,
  } as any)
const AuthDashboardProjectsProjectIdSettingsIndexRoute =
  AuthDashboardProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardProjectsProjectIdSettingsRouteRoute,
  } as any)
const AuthDashboardProjectsProjectIdDeploymentsIndexRoute =
  AuthDashboardProjectsProjectIdDeploymentsIndexRouteImport.update({
    id: '/deployments/',
    path: '/deployments/',
    getParentRoute: () => AuthDashboardProjectsProjectIdRouteRoute,
  } as any)
const AuthDashboardProjectsProjectIdSettingsGeneralRoute =
  AuthDashboardProjectsProjectIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthDashboardProjectsProjectIdSettingsRouteRoute,
  } as any)
const AuthDashboardProjectsProjectIdSettingsEnvironmentRoute =
  AuthDashboardProjectsProjectIdSettingsEnvironmentRouteImport.update({
    id: '/environment',
    path: '/environment',
    getParentRoute: () => AuthDashboardProjectsProjectIdSettingsRouteRoute,
  } as any)
const AuthDashboardProjectsProjectIdSettingsDomainsRoute =
  AuthDashboardProjectsProjectIdSettingsDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthDashboardProjectsProjectIdSettingsRouteRoute,
  } as any)
const AuthDashboardProjectsProjectIdDeploymentsDeploymentIdIndexRoute =
  AuthDashboardProjectsProjectIdDeploymentsDeploymentIdIndexRouteImport.update({
    id: '/deployments/$deploymentId/',
    path: '/deployments/$deploymentId/',
    getParentRoute: () => AuthDashboardProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/n8n': typeof N8nRoute
  '/using-module-component': typeof UsingModuleComponentRoute
  '/logout': typeof AuthLogoutRoute
  '/example': typeof ExampleIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/stripe': typeof StripeIndexRoute
  '/dashboard': typeof AuthDashboardDashboardRoute
  '/intro-flow': typeof AuthDashboardIntroFlowRoute
  '/settings': typeof AuthDashboardSettingsRoute
  '/projects/$projectId': typeof AuthDashboardProjectsProjectIdRouteRouteWithChildren
  '/projects': typeof AuthDashboardProjectsIndexRoute
  '/projects/$projectId/settings': typeof AuthDashboardProjectsProjectIdSettingsRouteRouteWithChildren
  '/projects/$projectId/': typeof AuthDashboardProjectsProjectIdIndexRoute
  '/projects/$projectId/settings/domains': typeof AuthDashboardProjectsProjectIdSettingsDomainsRoute
  '/projects/$projectId/settings/environment': typeof AuthDashboardProjectsProjectIdSettingsEnvironmentRoute
  '/projects/$projectId/settings/general': typeof AuthDashboardProjectsProjectIdSettingsGeneralRoute
  '/projects/$projectId/deployments': typeof AuthDashboardProjectsProjectIdDeploymentsIndexRoute
  '/projects/$projectId/settings/': typeof AuthDashboardProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/deployments/$deploymentId': typeof AuthDashboardProjectsProjectIdDeploymentsDeploymentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/n8n': typeof N8nRoute
  '/using-module-component': typeof UsingModuleComponentRoute
  '/logout': typeof AuthLogoutRoute
  '/example': typeof ExampleIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/stripe': typeof StripeIndexRoute
  '/dashboard': typeof AuthDashboardDashboardRoute
  '/intro-flow': typeof AuthDashboardIntroFlowRoute
  '/settings': typeof AuthDashboardSettingsRoute
  '/projects': typeof AuthDashboardProjectsIndexRoute
  '/projects/$projectId': typeof AuthDashboardProjectsProjectIdIndexRoute
  '/projects/$projectId/settings/domains': typeof AuthDashboardProjectsProjectIdSettingsDomainsRoute
  '/projects/$projectId/settings/environment': typeof AuthDashboardProjectsProjectIdSettingsEnvironmentRoute
  '/projects/$projectId/settings/general': typeof AuthDashboardProjectsProjectIdSettingsGeneralRoute
  '/projects/$projectId/deployments': typeof AuthDashboardProjectsProjectIdDeploymentsIndexRoute
  '/projects/$projectId/settings': typeof AuthDashboardProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/deployments/$deploymentId': typeof AuthDashboardProjectsProjectIdDeploymentsDeploymentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/n8n': typeof N8nRoute
  '/using-module-component': typeof UsingModuleComponentRoute
  '/_auth/_dashboard': typeof AuthDashboardRouteWithChildren
  '/_auth/logout': typeof AuthLogoutRoute
  '/example/': typeof ExampleIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/stripe/': typeof StripeIndexRoute
  '/_auth/_dashboard/dashboard': typeof AuthDashboardDashboardRoute
  '/_auth/_dashboard/intro-flow': typeof AuthDashboardIntroFlowRoute
  '/_auth/_dashboard/settings': typeof AuthDashboardSettingsRoute
  '/_auth/_dashboard/projects/$projectId': typeof AuthDashboardProjectsProjectIdRouteRouteWithChildren
  '/_auth/_dashboard/projects/': typeof AuthDashboardProjectsIndexRoute
  '/_auth/_dashboard/projects/$projectId/settings': typeof AuthDashboardProjectsProjectIdSettingsRouteRouteWithChildren
  '/_auth/_dashboard/projects/$projectId/': typeof AuthDashboardProjectsProjectIdIndexRoute
  '/_auth/_dashboard/projects/$projectId/settings/domains': typeof AuthDashboardProjectsProjectIdSettingsDomainsRoute
  '/_auth/_dashboard/projects/$projectId/settings/environment': typeof AuthDashboardProjectsProjectIdSettingsEnvironmentRoute
  '/_auth/_dashboard/projects/$projectId/settings/general': typeof AuthDashboardProjectsProjectIdSettingsGeneralRoute
  '/_auth/_dashboard/projects/$projectId/deployments/': typeof AuthDashboardProjectsProjectIdDeploymentsIndexRoute
  '/_auth/_dashboard/projects/$projectId/settings/': typeof AuthDashboardProjectsProjectIdSettingsIndexRoute
  '/_auth/_dashboard/projects/$projectId/deployments/$deploymentId/': typeof AuthDashboardProjectsProjectIdDeploymentsDeploymentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/n8n'
    | '/using-module-component'
    | '/logout'
    | '/example'
    | '/invoices'
    | '/stripe'
    | '/dashboard'
    | '/intro-flow'
    | '/settings'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/settings/domains'
    | '/projects/$projectId/settings/environment'
    | '/projects/$projectId/settings/general'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/settings/'
    | '/projects/$projectId/deployments/$deploymentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/n8n'
    | '/using-module-component'
    | '/logout'
    | '/example'
    | '/invoices'
    | '/stripe'
    | '/dashboard'
    | '/intro-flow'
    | '/settings'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/settings/domains'
    | '/projects/$projectId/settings/environment'
    | '/projects/$projectId/settings/general'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/deployments/$deploymentId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/login'
    | '/n8n'
    | '/using-module-component'
    | '/_auth/_dashboard'
    | '/_auth/logout'
    | '/example/'
    | '/invoices/'
    | '/stripe/'
    | '/_auth/_dashboard/dashboard'
    | '/_auth/_dashboard/intro-flow'
    | '/_auth/_dashboard/settings'
    | '/_auth/_dashboard/projects/$projectId'
    | '/_auth/_dashboard/projects/'
    | '/_auth/_dashboard/projects/$projectId/settings'
    | '/_auth/_dashboard/projects/$projectId/'
    | '/_auth/_dashboard/projects/$projectId/settings/domains'
    | '/_auth/_dashboard/projects/$projectId/settings/environment'
    | '/_auth/_dashboard/projects/$projectId/settings/general'
    | '/_auth/_dashboard/projects/$projectId/deployments/'
    | '/_auth/_dashboard/projects/$projectId/settings/'
    | '/_auth/_dashboard/projects/$projectId/deployments/$deploymentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  N8nRoute: typeof N8nRoute
  UsingModuleComponentRoute: typeof UsingModuleComponentRoute
  ExampleIndexRoute: typeof ExampleIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  StripeIndexRoute: typeof StripeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/using-module-component': {
      id: '/using-module-component'
      path: '/using-module-component'
      fullPath: '/using-module-component'
      preLoaderRoute: typeof UsingModuleComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n8n': {
      id: '/n8n'
      path: '/n8n'
      fullPath: '/n8n'
      preLoaderRoute: typeof N8nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe/': {
      id: '/stripe/'
      path: '/stripe'
      fullPath: '/stripe'
      preLoaderRoute: typeof StripeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/': {
      id: '/example/'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_dashboard': {
      id: '/_auth/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_dashboard/settings': {
      id: '/_auth/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthDashboardSettingsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/_dashboard/intro-flow': {
      id: '/_auth/_dashboard/intro-flow'
      path: '/intro-flow'
      fullPath: '/intro-flow'
      preLoaderRoute: typeof AuthDashboardIntroFlowRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/_dashboard/dashboard': {
      id: '/_auth/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardDashboardRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/_dashboard/projects/': {
      id: '/_auth/_dashboard/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthDashboardProjectsIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/_dashboard/projects/$projectId': {
      id: '/_auth/_dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthDashboardProjectsProjectIdRouteRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/_dashboard/projects/$projectId/': {
      id: '/_auth/_dashboard/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthDashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthDashboardProjectsProjectIdRouteRoute
    }
    '/_auth/_dashboard/projects/$projectId/settings': {
      id: '/_auth/_dashboard/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthDashboardProjectsProjectIdSettingsRouteRouteImport
      parentRoute: typeof AuthDashboardProjectsProjectIdRouteRoute
    }
    '/_auth/_dashboard/projects/$projectId/settings/': {
      id: '/_auth/_dashboard/projects/$projectId/settings/'
      path: '/'
      fullPath: '/projects/$projectId/settings/'
      preLoaderRoute: typeof AuthDashboardProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof AuthDashboardProjectsProjectIdSettingsRouteRoute
    }
    '/_auth/_dashboard/projects/$projectId/deployments/': {
      id: '/_auth/_dashboard/projects/$projectId/deployments/'
      path: '/deployments'
      fullPath: '/projects/$projectId/deployments'
      preLoaderRoute: typeof AuthDashboardProjectsProjectIdDeploymentsIndexRouteImport
      parentRoute: typeof AuthDashboardProjectsProjectIdRouteRoute
    }
    '/_auth/_dashboard/projects/$projectId/settings/general': {
      id: '/_auth/_dashboard/projects/$projectId/settings/general'
      path: '/general'
      fullPath: '/projects/$projectId/settings/general'
      preLoaderRoute: typeof AuthDashboardProjectsProjectIdSettingsGeneralRouteImport
      parentRoute: typeof AuthDashboardProjectsProjectIdSettingsRouteRoute
    }
    '/_auth/_dashboard/projects/$projectId/settings/environment': {
      id: '/_auth/_dashboard/projects/$projectId/settings/environment'
      path: '/environment'
      fullPath: '/projects/$projectId/settings/environment'
      preLoaderRoute: typeof AuthDashboardProjectsProjectIdSettingsEnvironmentRouteImport
      parentRoute: typeof AuthDashboardProjectsProjectIdSettingsRouteRoute
    }
    '/_auth/_dashboard/projects/$projectId/settings/domains': {
      id: '/_auth/_dashboard/projects/$projectId/settings/domains'
      path: '/domains'
      fullPath: '/projects/$projectId/settings/domains'
      preLoaderRoute: typeof AuthDashboardProjectsProjectIdSettingsDomainsRouteImport
      parentRoute: typeof AuthDashboardProjectsProjectIdSettingsRouteRoute
    }
    '/_auth/_dashboard/projects/$projectId/deployments/$deploymentId/': {
      id: '/_auth/_dashboard/projects/$projectId/deployments/$deploymentId/'
      path: '/deployments/$deploymentId'
      fullPath: '/projects/$projectId/deployments/$deploymentId'
      preLoaderRoute: typeof AuthDashboardProjectsProjectIdDeploymentsDeploymentIdIndexRouteImport
      parentRoute: typeof AuthDashboardProjectsProjectIdRouteRoute
    }
  }
}

interface AuthDashboardProjectsProjectIdSettingsRouteRouteChildren {
  AuthDashboardProjectsProjectIdSettingsDomainsRoute: typeof AuthDashboardProjectsProjectIdSettingsDomainsRoute
  AuthDashboardProjectsProjectIdSettingsEnvironmentRoute: typeof AuthDashboardProjectsProjectIdSettingsEnvironmentRoute
  AuthDashboardProjectsProjectIdSettingsGeneralRoute: typeof AuthDashboardProjectsProjectIdSettingsGeneralRoute
  AuthDashboardProjectsProjectIdSettingsIndexRoute: typeof AuthDashboardProjectsProjectIdSettingsIndexRoute
}

const AuthDashboardProjectsProjectIdSettingsRouteRouteChildren: AuthDashboardProjectsProjectIdSettingsRouteRouteChildren =
  {
    AuthDashboardProjectsProjectIdSettingsDomainsRoute:
      AuthDashboardProjectsProjectIdSettingsDomainsRoute,
    AuthDashboardProjectsProjectIdSettingsEnvironmentRoute:
      AuthDashboardProjectsProjectIdSettingsEnvironmentRoute,
    AuthDashboardProjectsProjectIdSettingsGeneralRoute:
      AuthDashboardProjectsProjectIdSettingsGeneralRoute,
    AuthDashboardProjectsProjectIdSettingsIndexRoute:
      AuthDashboardProjectsProjectIdSettingsIndexRoute,
  }

const AuthDashboardProjectsProjectIdSettingsRouteRouteWithChildren =
  AuthDashboardProjectsProjectIdSettingsRouteRoute._addFileChildren(
    AuthDashboardProjectsProjectIdSettingsRouteRouteChildren,
  )

interface AuthDashboardProjectsProjectIdRouteRouteChildren {
  AuthDashboardProjectsProjectIdSettingsRouteRoute: typeof AuthDashboardProjectsProjectIdSettingsRouteRouteWithChildren
  AuthDashboardProjectsProjectIdIndexRoute: typeof AuthDashboardProjectsProjectIdIndexRoute
  AuthDashboardProjectsProjectIdDeploymentsIndexRoute: typeof AuthDashboardProjectsProjectIdDeploymentsIndexRoute
  AuthDashboardProjectsProjectIdDeploymentsDeploymentIdIndexRoute: typeof AuthDashboardProjectsProjectIdDeploymentsDeploymentIdIndexRoute
}

const AuthDashboardProjectsProjectIdRouteRouteChildren: AuthDashboardProjectsProjectIdRouteRouteChildren =
  {
    AuthDashboardProjectsProjectIdSettingsRouteRoute:
      AuthDashboardProjectsProjectIdSettingsRouteRouteWithChildren,
    AuthDashboardProjectsProjectIdIndexRoute:
      AuthDashboardProjectsProjectIdIndexRoute,
    AuthDashboardProjectsProjectIdDeploymentsIndexRoute:
      AuthDashboardProjectsProjectIdDeploymentsIndexRoute,
    AuthDashboardProjectsProjectIdDeploymentsDeploymentIdIndexRoute:
      AuthDashboardProjectsProjectIdDeploymentsDeploymentIdIndexRoute,
  }

const AuthDashboardProjectsProjectIdRouteRouteWithChildren =
  AuthDashboardProjectsProjectIdRouteRoute._addFileChildren(
    AuthDashboardProjectsProjectIdRouteRouteChildren,
  )

interface AuthDashboardRouteChildren {
  AuthDashboardDashboardRoute: typeof AuthDashboardDashboardRoute
  AuthDashboardIntroFlowRoute: typeof AuthDashboardIntroFlowRoute
  AuthDashboardSettingsRoute: typeof AuthDashboardSettingsRoute
  AuthDashboardProjectsProjectIdRouteRoute: typeof AuthDashboardProjectsProjectIdRouteRouteWithChildren
  AuthDashboardProjectsIndexRoute: typeof AuthDashboardProjectsIndexRoute
}

const AuthDashboardRouteChildren: AuthDashboardRouteChildren = {
  AuthDashboardDashboardRoute: AuthDashboardDashboardRoute,
  AuthDashboardIntroFlowRoute: AuthDashboardIntroFlowRoute,
  AuthDashboardSettingsRoute: AuthDashboardSettingsRoute,
  AuthDashboardProjectsProjectIdRouteRoute:
    AuthDashboardProjectsProjectIdRouteRouteWithChildren,
  AuthDashboardProjectsIndexRoute: AuthDashboardProjectsIndexRoute,
}

const AuthDashboardRouteWithChildren = AuthDashboardRoute._addFileChildren(
  AuthDashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRouteWithChildren
  AuthLogoutRoute: typeof AuthLogoutRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRouteWithChildren,
  AuthLogoutRoute: AuthLogoutRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  N8nRoute: N8nRoute,
  UsingModuleComponentRoute: UsingModuleComponentRoute,
  ExampleIndexRoute: ExampleIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  StripeIndexRoute: StripeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
