/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsingModuleComponentImport } from './routes/using-module-component'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ExampleIndexImport } from './../../modules/template/frontend/src/routes/example/index'

// Create/Update Routes

const UsingModuleComponentRoute = UsingModuleComponentImport.update({
  id: '/using-module-component',
  path: '/using-module-component',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExampleIndexRoute = ExampleIndexImport.update({
  id: '/example/',
  path: '/example/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/using-module-component': {
      id: '/using-module-component'
      path: '/using-module-component'
      fullPath: '/using-module-component'
      preLoaderRoute: typeof UsingModuleComponentImport
      parentRoute: typeof rootRoute
    }
    '/example/': {
      id: '/example/'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/using-module-component': typeof UsingModuleComponentRoute
  '/example': typeof ExampleIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/using-module-component': typeof UsingModuleComponentRoute
  '/example': typeof ExampleIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/using-module-component': typeof UsingModuleComponentRoute
  '/example/': typeof ExampleIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/using-module-component' | '/example'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/using-module-component' | '/example'
  id: '__root__' | '/' | '/about' | '/using-module-component' | '/example/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  UsingModuleComponentRoute: typeof UsingModuleComponentRoute
  ExampleIndexRoute: typeof ExampleIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UsingModuleComponentRoute: UsingModuleComponentRoute,
  ExampleIndexRoute: ExampleIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/using-module-component",
        "/example/"
      ]
    },
    "/": {
      "filePath": "./index.tsx"
    },
    "/about": {
      "filePath": "./about.tsx"
    },
    "/using-module-component": {
      "filePath": "./using-module-component.tsx"
    },
    "/example/": {
      "filePath": "../../../modules/template/frontend/src/routes/example/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
